1. Create a 5X2 integer array from a range between 100 to 
200 such that the difference between each element is 10


In [4]:
import numpy as np

arr = np.arange(100,200,10).reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


2. Write a NumPy program to create a 3x3x3 array filled
with arbitrary values and find the minimum and maximum
values.


In [17]:
import random
arbi = np.random.random((3,3,3))
print(arbi)

print ("Max from Arbitory values:",arbi.max())
print ("Max from Arbitory values:",arbi.min())


[[[0.44478782 0.62062896 0.69514519]
  [0.07554583 0.24669357 0.7472799 ]
  [0.8584613  0.70492215 0.53596586]]

 [[0.00184068 0.16151947 0.85065331]
  [0.6109966  0.79450351 0.49142243]
  [0.86770157 0.31991332 0.95815445]]

 [[0.57913537 0.94949822 0.48000235]
  [0.95289486 0.14887887 0.69994676]
  [0.36243171 0.37605537 0.47984684]]]
Max from Arbitory values: 0.95815445120581
Max from Arbitory values: 0.0018406803769207558


3. Write a NumPy program to create a 5x5 zero matrix
with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [18]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


4. Given an array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9
i) Extract all odd numbers from arr
ii) Replace all odd numbers in arr with -1


In [28]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print ("Odd values from the numpy array",arr[arr%2 != 0])
arr[arr%2 != 0] = -1
print ("Replaced -1 value for odd values in array",arr)


Odd values from the numpy array [1 3 5 7 9]
Replaced -1 value for odd values in array [ 0 -1  2 -1  4 -1  6 -1  8 -1]


5.Write a NumPy program to create a 3x3 identity matrix,
i.e. diagonal elements are 1,the rest are 0.

In [32]:
arr = np.eye(3,3,dtype=int)
print ("Identity matrix:",arr)

Identity matrix: [[1 0 0]
 [0 1 0]
 [0 0 1]]


6. Write a NumPy program to convert an array to a float
type.

In [35]:
arr = arr.astype(float)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7. Write a NumPy program to generate five random
numbers from the normal distribution.

In [36]:
x = np.random.normal(size=5)
print(x)

[-1.31035266 -0.54488669 -2.20740174 -0.61354409  0.32123099]


8. Following is the input NumPy array delete column two
and insert following new column in its place.
sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,
66]])
newColumn = numpy.array([[10,10,10]])

In [38]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94, 66]])
newColumn = np.array([[10,10,10]])

sampleArray[1]= newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

9. Write a NumPy program to compute the multiplication
of two given matrices.


In [59]:
x1 = np.random.randint(1,5,size=(3,3))
x2 = np.random.randint(1,5,size=(3,3))
x3 = x1 * x2
print ("x1",x1)
print ("x2",x2)
print ("multiplication",x3)

x1 [[1 4 4]
 [1 1 3]
 [3 4 2]]
x2 [[2 4 3]
 [1 4 3]
 [4 2 2]]
multiplication [[ 2 16 12]
 [ 1  4  9]
 [12  8  4]]


10. Write a NumPy program to create a random vector of
size 10 and sort it.


In [65]:
vector = np.random.random(size=10)
print ("numpy sorted array",np.sort(vector))

[0.36110228 0.58779381 0.6487758  0.69020889 0.73379812 0.75969543
 0.78347581 0.87418069 0.91800988 0.99661485]


11. Write a NumPy program to compute the covariance
matrix of two arrays.


In [66]:
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


12.Create a 4X2 integer array and Prints its :
i)The shape of an array.
ii) Array dimensions.
iii) The Length of each element of the array in bytes

In [75]:
intarr = np.random.randint(0,100,size=(4,2))
print ("Shape of array",intarr.shape)
print ("array dimension",intarr.ndim)
print ("size of each element",intarr.itemsize)

Shape of array (4, 2)
array dimension 2
size of each element 4


13. Write a NumPy program to concatenate element-wise
two arrays of string.

In [83]:
a1 = np.array(["a","b","c"])
a2 = np.array(["d","e","f"])
print ("matrix1",a1)
print ("matrix2",a2)
a3 = np.char.add(a1, a2)
print ("concate matrix3",a3)

matrix1 ['a' 'b' 'c']
matrix2 ['d' 'e' 'f']
concate matrix3 ['ad' 'be' 'cf']


14. Write a NumPy program to capitalize the first letter,
lowercase, uppercase, swapcase, title-case of all the
elements of a given array.

In [84]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:", x)

capital = np.char.capitalize(x)
lower = np.char.lower(x)
upper = np.char.upper(x)
swap = np.char.swapcase(x)
title = np.char.title(x)
print("\nCapital: ", capital)
print("Lower: ", lower)
print("Upper: ", upper)
print("Swap: ", swap)
print("Title: ", title)

Original Array: ['python' 'PHP' 'java' 'C++']

Capital:  ['Python' 'Php' 'Java' 'C++']
Lower:  ['python' 'php' 'java' 'c++']
Upper:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swap:  ['PYTHON' 'php' 'JAVA' 'c++']
Title:  ['Python' 'Php' 'Java' 'C++']


15. Write a NumPy program to convert a given array into a list.

In [92]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str).tolist()
print ("array as list from numpy:",x)

array as list from numpy: ['python', 'PHP', 'java', 'C++']


16. Write a NumPy program to compute the sum of all
elements, sum of each column and sum of each row of a
given array.

In [96]:
x1 = np.random.randint(1,5,size=(3,3))
print ("matrix",x1)
print ("sum of all elements ",np.sum(x1))
print ("sum column wise",np.sum(x1,axis=0))
print ("sum row wise",np.sum(x1,axis=1))

matrix [[4 1 1]
 [3 3 3]
 [4 4 4]]
sum of all elements  27
sum column wise [11  8  8]
sum row wise [ 6  9 12]


17. Write a NumPy program to create a random 10x4
array and extract the first five rows of the array and store
them into a variable.

In [100]:
x1 = np.random.randint(1,100,size=(10,4))
print ("matrix",x1)
print ("###########################")
listof_five = x1[:6]
print ("list with first 5 rows",listof_five)

matrix [[76 35  9 21]
 [70 38 20 76]
 [16 89 35 86]
 [43 31  1 81]
 [22 48 64 66]
 [ 3 95 95 47]
 [83 40 57 36]
 [10 53 23 94]
 [26  7  3 94]
 [ 8 13 91 71]]
###########################
list with first 5 rows [[76 35  9 21]
 [70 38 20 76]
 [16 89 35 86]
 [43 31  1 81]
 [22 48 64 66]
 [ 3 95 95 47]]


18. Write a NumPy program to get the unique elements of
a 1D and 2D array.


In [101]:
import numpy as np
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]



19. Write a NumPy program to get the unique elements of
an array.
arr= [-10 12.12 -0.2]


In [13]:
import numpy as np
arr = [-10, 12., 12, -0.2]
narr = np.array(arr)
print (narr)
print ("unique elem from given array",np.unique(narr))

[-10.   12.   12.   -0.2]
unique elem from given array [-10.   -0.2  12. ]


20. Write a NumPy program to save a given array to a text
file and load it. You have to save and load files using
numpy library .

In [23]:
import random
arr = np.random.randint(0,100,size=(3,3))
print ("random array",arr)
header="'h1','h2','h3'"
np.savetxt('nptemp.txt',arr,header=header)
fileout = np.loadtxt('nptemp.txt')
print ("contents from file",fileout)

random array [[97 26 77]
 [24 93 23]
 [43 59 15]]
contents from file [[97. 26. 77.]
 [24. 93. 23.]
 [43. 59. 15.]]
